import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins =Poppins({
  weight:['100','200','300','400','500','600']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
        <header className="py-2 max-w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="py-2 max-w-11/12 mx-auto">
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
